name: CI/CD Pipeline

on:
  push:
    branches:
      - orginal

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      run: |
        cd /home/gracilin/builder
        bash deploy-react.sh "$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')"
